### ISSUE TITLE
PDF exporting

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#27]
# Reports

PDF exporting supports the following reports depending on current view

- **Action report** from action view
  - action page (or more pages when specified - see below)
  - recommendations page (related recommendations)
- **Category report** from category view
  - Section A
    - current category page, 
    - reference page for current category
  - Section B
    - one page for every related action (or more pages when specified - see below)
  - Appendix (Nice to have)
    - recommendations page(s)  (all recommendations related to category - and actions?)
- **Full report** from "all actions" view (unfiltered)  
  - title page 
  - Section A
    - all category pages
    - reference pages for all categories 
  - Section B
    - one page for every action  (or more pages when specified - see below)
  - Appendix (Nice to have)
    - recommendations pages (all recommendations) 
- **Custom report** from "all actions" (filtered) and search views
  - title page
  - Section A
    - all related category pages (?)
    - a reference page (category-unspecific - ?) 
  - Section B
    - one page for every action that match current filters or search term    
  - Appendix (Nice to have)
    - recommendations page(s)  (all recommendations related to actions)

# Pages

### Action page
Includes all fields as on web version, incl list of recommendation numbers. 1 or more pages per action. 

### Title page
Includes 
- Report title & claim
- Current filter settings
- Date
- ISBN ?
- Logo 
- Website link

### Category pages
Include all fields as on web version.

### Reference pages
List of actions with page number reference - one for each category for full report and category reports or for all filtered actions for custom report from filtered all action and search views

### Recommendation pages
List of recommendations

**Comment by tmfrnz** [comment]
![custom report](https://cloud.githubusercontent.com/assets/5811956/11178132/877b9602-8caf-11e5-90f2-5a8609c9b794.png)
![full report](https://cloud.githubusercontent.com/assets/5811956/11178133/877c3c1a-8caf-11e5-9984-50a7b60ea79d.png)
![single and category reports](https://cloud.githubusercontent.com/assets/5811956/11178134/8780926a-8caf-11e5-94b8-f4e0bfed84bc.png)

**Comment by rdoc101** [comment]
For the full report as each action belongs to a agency, a group and an issue how should the categories be expressed. Will be easy if it is just say the list of issue types where each issue category represents this 'Category 1 page' piece in the above image and then the currently 97 issues listed in the action index, but if it is all categories from all types then there will be the currently 97 actions listed 3 times in each of the action indexes. Of course wouldn't need all the individual 97 actions printed 3 times but need clarification on whether there should be all 97 actions in each action index.

**Comment by tmfrnz** [comment]
For the full and custom reports our initial thinking was to print an action index for each type and category (full report: 38 category pages, each with own action index page(s)). So yes, each action would be listed (at least) 3 times - for at least one issue, at least one group and at least one agency.

**Comment by rdoc101** [comment]
Ok, is there some preference for order of these?

**Comment by tmfrnz** [comment]
Actions should be ordered by id, not sure about categories at this stage (by type and alphabetically or by type and action count) - will seek confirmation

**Comment by tmfrnz** [comment]
@rdoc101 feel free to suggest an alternative option if you can think of one - thanks

**Comment by tmfrnz** [comment]
Page-numbering: to keep it easy for now for all actions and category reports, page numbering will restart for the actions. Category and index pages will be numbered A1, A2, ... and action pages will be numbered B1, B2, ...

To allow action pages occupy more than 1 page (eg action 55) and still be able to define the page number (as needed for the category specific index) we will add a column to the actions table to specify the number of pages for those actions (default to 1)

**Comment by rdoc101** [comment]
Ah, this printnoofpages will probably be a good easy solution to the action problem. 
I will build this in tomorrow.

**Comment by rdoc101** [comment]
Have updated the index pages so that they should now have accurate page numbers. But the problem is that some of the category description are sprawling over two pages, so when exporting the full report the start of the action section isn't known as was with the action pages index before. To solve this probably the easiest option is to just change fonts to one with less line height so that no category descriptions go over a single page. At the moment it is using roboto as the default...

**Comment by tmfrnz** [comment]
To solve this we will simply divide the report into sections so we can
restart the numbering.

**Comment by tmfrnz** [comment]
See comment above. Actions will be B1, B2, etc

**Comment by rdoc101** [comment]
Eh the thing is that the function pdfmake uses for its footer/header section is just given the current page number and the total number of pages, which is calculated on rendering the document. So to restart the page numbering eg B1, B2, in the second section the page on which that will occur needs to be known (which isn't known until after rendering). I was estimating this current page by multiplying the number of categorys by 2 (assuming a category page + action index page) but of course this fails if the category page is over a page. 

So if by sections you mean two seperate documents this could possibly work as to not having to care about restarting the page numbers in that document, but seems not so ideal. Unfortunately pdfmake doesn't have the ability to concatenate two documents together into one.

**Comment by dumpark** [comment]
Ok so will either have to set the page numbers outside of the footer or
fork and tweak pdfmake's footer function.

**Comment by rdoc101** [comment]
I found a tweak to pdfmake here https://github.com/bpampuch/pdfmake/issues/283 which enables the sections to be defined before rendering the footers which works pretty ok. Just need to tidy it up a bit and then will publish it tomorrow.

**Comment by dumpark** [comment]
Hi Richard,

Hope all is well in Kakapo land...

Thanks for your continued work on the NPA - how did you get on with the
page numbers?

If you get back to Christchurch this week how about we have a little catch
up before the break?

By the way we have decided to go on a camping trip to the south island this
Christmas break so may reach out to you if we happen to come through
Christchurch at some stage...

Cheers,
Timo





On 11 December 2015 at 23:23, Richard Flett <notifications@github.com>
wrote:

> I found a tweak to pdfmake here bpampuch/pdfmake#283
> <https://github.com/bpampuch/pdfmake/issues/283> which enables the
> sections to be defined before rendering the footers which works pretty ok.
> Just need to tidy it up a bit and then will publish it tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hrcnz/npa/issues/27#issuecomment-163902939>.
>



-- 
[image: dumpark] <http://dumpark.com/>

Timo Franz Head of Development | *dumpark.com <http://dumpark.com>*
timo@dumpark.com T +64 04 381 3725 M +64 022 011 8070 SKYPE tmfrnz

**Comment by dmprk** [comment]
Please find the updated pdf layout attached

[NPA-pdf-report-layout-01-update150119.pdf](https://github.com/hrcnz/npa/files/95108/NPA-pdf-report-layout-01-update150119.pdf)

**Comment by tmfrnz** [comment]
pdfmake library and vfs_fonts add >1MB to bundle.js - better load those only when needed?
