### ISSUE TITLE
PDF exporting: parse markdown

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#45]

**Comment by tmfrnz** [comment]
We will have to create a custom print renderer (similar to utils/parse-markdown) that converts it to pdf-make document definition text instead of html by overriding the renderer methods:
https://github.com/chjj/marked

**Comment by tmfrnz** [comment]
added simple html-to-pdf parser based on
https://github.com/ymkins/html2pdfmake

**Comment by tmfrnz** [comment]
Parsing required for action (description, desiredoutcome, measures) and category fields (main, side)

**Comment by tmfrnz** [comment]
@rdoc101 can you try replacing the jquery dependency in /utils/parse-html.js?

**Comment by rdoc101** [comment]
alright

**Comment by rdoc101** [comment]
Rewrote the part of this file using jquery with some vanilla js. So have also removed jquery from the package.json file
