### ISSUE TITLE
PDF Exporting: Performance for large files

### ISSUE THREAD

**Issue by rdoc101** [hrcnz/npa#47]
When an export gets rather large the amount of time to create the pdf gets rather long.

Other similar issues noticed with pdfmake....
https://github.com/bpampuch/pdfmake/issues/38
http://stackoverflow.com/questions/32689932/how-to-apply-web-worker-to-rendering-of-a-pdf-using-makepdf/33206568#33206568
https://github.com/bpampuch/pdfmake/issues/153
https://github.com/bpampuch/pdfmake/issues/280
https://github.com/bpampuch/pdfmake/issues/342

Have tried putting in Number.MAX_SAFE_INTEGER and rebuilding pdfmake as mentioned in the https://github.com/bpampuch/pdfmake/issues/280 but for me it didn't do anything.

**Comment by rdoc101** [comment]
Have built a lot of the dependencies from scratch again. And instead of using the pdfmake-browserified switching to just pdfmake and requiring the individual files needed. Doing both of this has cut rendering time from ~4 mins down to less than 10sec for the full report. 
Follow https://github.com/bpampuch/pdfmake/issues/280 for updates is the best. Maybe it will actually be merged into pdfmake eventually.

**Comment by tmfrnz** [comment]
Excellent! Did you test for different browsers?

**Comment by rdoc101** [comment]
Just for firefox and chrome so far.

  

Both are about the same time of around 10 seconds on my machine.

  

Will crank up my windows vm and see how ie goes.

> On Jan 13 2016, at 2:50 pm, Timo Franz &lt;notifications@github.com&gt;
wrote:  

>

> Excellent! Did you test for different browsers?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/hrcnz/n
pa/issues/47#issuecomment-171127500).![](https://github.com/notifications/beac
on/AA0gA4e-hkNXYSvW4ZrfiUSWX3LgA4nRks5pZaTRgaJpZM4GxjRi.gif)

**Comment by rdoc101** [comment]
I tested it in IE11 on my windows Virtual Machine, which has a pretty limited
amount of memory assigned to it and it managed to produce the pdf without
timing out or crashing or whatever. But did take a approx ~2 minutes. I might
look into doing one other thing listed in a few github issues to see if this
can be improved a bit more. It probably is going to need some real world
testing though to see if it is stable enough.

> On Jan 13 2016, at 3:22 pm, Richard Flett &lt;richardflett@gmail.com&gt;
wrote:  
Just for firefox and chrome so far.

>

>  

>

> Both are about the same time of around 10 seconds on my machine.

>

>  

>

> Will crank up my windows vm and see how ie goes.

>

>> On Jan 13 2016, at 2:50 pm, Timo Franz &lt;notifications@github.com&gt;
wrote:  

>>

>> Excellent! Did you test for different browsers?

>>

>> —  
Reply to this email directly or [view it on GitHub](https://github.com/hrcnz/n
pa/issues/47#issuecomment-171127500).![](https://github.com/notifications/beac
on/AA0gA4e-hkNXYSvW4ZrfiUSWX3LgA4nRks5pZaTRgaJpZM4GxjRi.gif)

**Comment by tmfrnz** [comment]
If you think it is a VM limitation I can also do a quick IE test

**Comment by rdoc101** [comment]
If you would like too that would be good as I don't have access to a native
windows machine.

**Comment by tmfrnz** [comment]
__Test results for IE__
IE 11: <1min
IE 10 (emulator): <1min
IE 9 (emulator): Error "SCRIPT5022: Could not generate blob" after ~40s (see https://github.com/bpampuch/pdfmake/pull/475/files)
