### ISSUE TITLE
PDF exporting: Add images

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#49]

**Comment by tmfrnz** [comment]
PDF images have been added to https://github.com/hrcnz/npa/tree/8ce5bbd282c1f17cdc5b7b5bbdb44f7beedc66cd/app/src/img/pdf-icons

**Comment by rdoc101** [comment]
Images are now in the document.

**Comment by tmfrnz** [comment]
Image quality is still unsatisfactory - will set up a test case to evaluate different options
