### ISSUE TITLE
PDF exporting: add lines and other geometric shapes as vector graphics

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#50]
http://pdfkit.org/docs/vector.html

**Comment by tmfrnz** [comment]
Vector elements are added using the canvas
https://github.com/bpampuch/pdfmake/blob/af47c2757d6775c61dea48a9c0923e52231408e3/examples/vectors.js

The frontpage background shape can probably best be achieved using the polyline type

**Comment by rdoc101** [comment]
Front page background shape is loaded as with the polyline type above now.
Same with lines. Might need to make them slightly skinner still.

Last bit needed is to have the grey background on page numbers on the related actions index page.
