### ISSUE TITLE
Category View (v2)

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#55]
Tablet/Desktop version (see p3 of invision layout #56)
Mobile version (see p16)

- ~~apply new colour scheme~~
- ~~remove text from category navigation~~
- ~~make category labels plural as per design (Issue > Issues, Treaty Bodies should however be UN Treaty Bodies)~~
- ~~change view title to simple plural (eg Issues)~~
- adjust column headers as per design
- ~~replace icon (new icon should become active with updated image sprite)~~

**Comment by rdoc101** [comment]
-_ adjust column headers as per design _
Have changed styles to be capitalised and not bold.
