### ISSUE TITLE
Colour Palette & Fonts v2

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#57]
"black" #263238 (default font colour)
"dark gray" #78909C (secondary font colour)
"darker gray" #627A85 (font colour for category navigation and filter panels - on light blue background)

"blue" #029BE5 (header background and for links/buttons, also recommendation count and stacked bar chart (accepted))
"darker blue" #0383C9 (main category navigation, active/hover background, also footer background)
"darkest blue" #026B9F (stacked bar chart colour 2 "not accepted", also footer highlight)
"light blue" #EAF0F4 (category and filter panel backgrounds)

"green" #69A41E (category navigation active/hover, action bar graph, action count, SMART labels on action view, also category buttons on start view)
"dark green" #598E0C (category navigation active/hover on start screen)

**Comment by rdoc101** [comment]
Can i just have confirmation on what the title fonts are? 
Is it droid sans for the 'Mahere rautaki a motu' subheader??

**Comment by dmprk** [comment]
Hi there, we are only using Roboto as a font. The title fonts are: Roboto bold and Roboto light
