### ISSUE TITLE
Header component (v2)

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#58]
- ~~remove logo~~
- replace subtitle with Maori text
- ~~align title/subtitle with content area on left~~
- ~~move secondary navigation to very top right (still called nav-main.js in code, rename to nav-secondary)~~
- replace Terms with FAQ in secondary navigation
- update primary navigation as per design, ~~align items left with content below, search right of page~~ (~~still called nav-mode.js in code, rename to nav-primary~~)

also see pp16 for mobile layout #56

**Comment by rdoc101** [comment]
- Maori text now included
- updated primary navigation css.
