### ISSUE TITLE
Filters Panel

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#60]

**Comment by rdoc101** [comment]
Will the number of filter fields be fixed to three along the top row? Eg by Action, Issue, Gov Agency? Because if it is then I can put them into the bootstrap grid system eg col-md-4 for each one, instead of having the width calculated inline as it doesn't work very nicely on smaller screens.
(ref FiltersPanel.js line 85...)
`var width = Math.max(20,100/group.filters.length)`

**Comment by rdoc101** [comment]
Also in regards to the style of the of the drop downs select menu. Should it just be white background and black text, or should it keep in line with the light blue background/grey text. Eg:
![screenshot from 2016-02-05 14-27-43](https://cloud.githubusercontent.com/assets/860163/12835443/10030aba-cc15-11e5-8c29-140b6940acaa.png)

**Comment by dumpark** [comment]
The number of filters in the top group may change in the future. Maybe we
can override the width in the css for small screens, eg "width: 100%
important!"

**Comment by dumpark** [comment]
For the drop down we will provide a mockup shortly - for now maybe white
background and dark grey text

**Comment by tmfrnz** [comment]
a few more minor things to take care of
- center-align smart criteria
- enable 'hide filters' button on mobile view
- date select dropdown
  - hide today's date (.rw-footer)
  - adjust rw-header
- multiselects: use cursor=pointer for dropdown link (.hrc-filter-panel .rw-multiselect-wrapper::after

**Comment by tmfrnz** [comment]
also there is a warning message to investigate - probably caused by the react widget library
"Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Popup component."

**Comment by tmfrnz** [comment]
another issue is that for some reason the multiselect labels show the id instead of the full category titles when filter settings return 0 results, eg 
/#/all/actions?specific=false&issue=justice&assignable=false&resultoriented=true

**Comment by tmfrnz** [comment]
add additional close filter button at bottom of filter panel for small screens (use class visible-xs) as per design

**Comment by rdoc101** [comment]
Have addressed each of the list items above and also added in the filter button at the bottom.

**Comment by tmfrnz** [comment]
fix borders for recommendations filters

**Comment by rdoc101** [comment]
Applied a fix for the 'getting ids when filter is 0'. The multi select component value field had is being set by this line:  'typeof query[filter.by] === 'string' ? [query[filter.by]] : query[filter.by]' 
Which was returning the ids. 

So have made this look up references to the titles. Just reusing the way the options are referenced a few lines above. 

https://github.com/hrcnz/npa/commit/56fcb317578555520e3af91e49c93c031cdcfb12

**Comment by tmfrnz** [comment]
Update to default/advanced filters view
