### ISSUE TITLE
Replace css image sprite with svg icons

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#61]
find the v2 svg icons in /app/src/img/svg-icons

**Comment by rdoc101** [comment]
Have added icons to relevant classes. 
Still need to sort out what exact classes would be used in some scenarios such as the three state smart icons.

**Comment by rdoc101** [comment]
Just a note that has already been discussed: 
For icons that are needing to change specific colour on certain paths; if it is possible to just insert them as <svg> then we can do this. 
Currently because they are background-images this isn't possible.

**Comment by tmfrnz** [comment]
for the smart and other filter icons, css classes are defined in npa\app\src\node_modules\components\views\all\all.js

**Comment by tmfrnz** [comment]
also the dropdown tag icon (icon_close-small-white.svg)) has just been committed

**Comment by tmfrnz** [comment]
would be nice to have inline svg, fell free to give it a try, maybe even using https://github.com/matthewwithanm/react-inlinesvg

**Comment by tmfrnz** [comment]
Another interesting alternative to  consider could be
https://github.com/publitas/react-svg-icons
Requires React 0.14 however - see untested branch here https://github.com/hrcnz/npa/tree/react-0.14

**Comment by rdoc101** [comment]
Tried out both libraries. The react-inlinesvg library worked pretty well straight off the bat. Don't really have any negatives I can see straight away apart from having to include the path in the svg declaration. 
With the react-svg-icons library I found that it would not like the current svg format because of the inline styles inside the files. So I had to place the styling into a separate css file to get it to work. But upon doing that it was working fine.

**Comment by tmfrnz** [comment]
react-svg-icons cannot deal with style tags, but inline styles should be fine
https://github.com/publitas/react-svg-icons/issues/4

**Comment by tmfrnz** [comment]
could not get react-svg-icons to work. here the error messages encountered:
- Warning: Icon(...): React component classes must extend React.Component.
- Uncaught Invariant Violation: Icon.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.

@rdoc101 any ideas? maybe can you add a working test branch?

**Comment by rdoc101** [comment]
I put up a test branch 61-svg-icons. 
Put in a svg icon in src/img/svg-test/ (needs the assets built to include it in the path i placed in the package.json)
And then the rest is just in the search.js file. But there isnt anything special going on. So maybe something else causing your errors.

(This branch is for testing purposes only)

**Comment by tmfrnz** [comment]
managed to get it working and implemented it  - also added a new icon set
