### ISSUE TITLE
Search view

### ISSUE THREAD

**Issue by tmfrnz** [hrcnz/npa#63]

**Comment by tmfrnz** [comment]
changed layout so that type filters are now on right hand column to reduce movement when live searching

**Comment by tmfrnz** [comment]
also trying/considering to always have the full list of result types, also when 0 results are returned

**Comment by tmfrnz** [comment]
todo:
- style search field
- style result type filter item which now have 3 states
  - default: black/grey as per design
  - active: use blue color, not green
  - disabled: use lighter gray for font

**Comment by rdoc101** [comment]
Have put in a pull request for this. In terms of the column order I put some pull's and push's on them so that on mobile it is still on the top first.

**Comment by tmfrnz** [comment]
improved search algorithm to allow for multiple words and added input field autofocus
todo: consider debounce to allow for fast typing

**Comment by tmfrnz** [comment]
implemented debounce using react-debounce-input and prepare search target string on data load rather than with every match test
